### ISSUE TITLE
Mac OS X 11.0.1 build fails

### ISSUE THREAD

**Issue by ahcm** [h4llow3En/mac-notification-sys#27] opened 2020-12-01 01:47 UTC
[err.txt](https://github.com/h4llow3En/mac-notification-sys/files/5619778/err.txt)

**Comment by algoz098** [comment] 2021-01-21 15:08
had similar problem fixed by removing and reinstalling the xcode commandtools.

**Comment by schickling** [comment] 2022-02-15 08:48
Same problem on macOS 12.

**Closed** 2023-07-03 22:16 UTC

**Comment by schickling** [comment] 2023-07-04 07:12
@hoodie does closing mean the problem have been addressed in a new release? 🙏

**Comment by hoodie** [comment] 2023-07-04 07:18
no sorry, I should have written a comment here. I assume that the issue is related missing systems packages being installed
